server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        
        # сначала по uri, потом в папку по uri, потом на index.html
        try_files $uri $uri/ /index.html;
    }
}